const GET_POKEMONES = "GET_POKEMONES";
const SEARCH_POKEMONES = "SEARCH_POKEMONES";
const SORT_POKEMONES = "SORT_POKEMONES";
const ADD_POKEMONES = "ADD_POKEMONES";
const FILTER_POKEMONES = "FILTER_POKEMONES";
const ADD_TYPES = "ADD_TYPES";
const DETAIL_POKEMONES = "DETAIL_POKEMONES";

module.exports = {
    GET_POKEMONES,
    SEARCH_POKEMONES,
    SORT_POKEMONES,
    ADD_POKEMONES,
    FILTER_POKEMONES,
    ADD_TYPES,
    DETAIL_POKEMONES,
}